# Generated by Django 5.0.3 on 2024-03-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locusnews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('content', models.TextField()),
            ],
        ),
    ]
