# Generated by Django 5.0.3 on 2024-03-27 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locusnews', '0002_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
