# Generated by Django 5.0.3 on 2024-03-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locusnews', '0005_alter_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
